### PR TITLE
Add customizable conversion callback

### PR DESCRIPTION
**Pull request by patrickgalbraith**
Implementation for #27

### CODE REVIEW

**Comment by patrickgalbraith** [comment]
This will also remove the need for #20 and #26

**Comment by rufman** [comment]
+1 I really like this solution. Allows for much more flexibility

**Comment by kompot** [comment]
Need this one too, will use @patrickgalbraith branch for now.

**Comment by patrickgalbraith** [comment]
@domchristie Have you had a look at his yet??

**Comment by domchristie** [comment]
Sorry for the delay in getting back to you on this one. This is nice! :)

I think it’d make more sense (to me at least ;) if the callback was part of the `options` parameter, rather than as its own parameter. After all, It is optional, and there may be other functions/callbacks we need to add in the future.

Perhaps the naming of `callback` could be improved, too. Perhaps `process` would be suitable?

Thanks!

**Comment by patrickgalbraith** [comment]
@domchristie Done!

> I think it’d make more sense (to me at least ;) if the callback was part of the options parameter, rather than as its own parameter. After all, It is optional, and there may be other functions/callbacks we need to add in the future.

Done but I have also made the process callback run if you pass a function in place of the options parameter. This makes it a lot cleaner to use since you don't need to create an object with a single key just to run it and at this point you only have a single callback option. But it will be forward compatible since it also takes an object.

So this will work:

    humps.camelizeKeys(obj, function (key, convert) {
      return /^[A-Z0-9_]+$/.test(key) ? key : convert(key);
    });

    humps.decamelizeKeys(obj, function (key, convert, options) {
      return /^[A-Z0-9_]+$/.test(key) ? key : convert(key, options);
    });

And this will also work:

    humps.decamelizeKeys(obj, {
        separator: '-',
        process: function (key, convert, options) {
          return /^[A-Z0-9_]+$/.test(key) ? key : convert(key, options);
        }
    });

And in the future something like this would also work:

    humps.decamelizeKeys(obj, {
        process: function (key, convert, options) {
          return /^[A-Z0-9_]+$/.test(key) ? key : convert(key, options);
        },
        isNumerical: function (n) {
          // .... example
        }
    });

**Comment by domchristie** [comment]
> I have also made the process callback run if you pass a function in place of the options parameter

Cool. Given this library centres around _converting_, I think this is sensible.

Thanks!

**Comment by patrickgalbraith** [comment]
@domchristie Thanks for merging this!

You can probably review and potentially close #20 #22 #23 #24 #27 #29

**Pull request merged**
